const teams = [
  { code: 'B1', name: "BRACT's VISHWAKARMA INSTITUTE OF TECHNOLOGY, PUNE" },
  { code: 'M1', name: "THE ROBO-TECH FORUM" },
  { code: 'A1', name: "PICT Robotics" },
  { code: 'L1', name: "TEAM ROBOCON LDCE" },
  { code: 'H1', name: "SRM TEAM ROBOCON" },
  { code: 'J1', name: "Team Nirma Robocon" },
  { code: 'F1', name: "Team GECA-CS" },
  { code: 'C1', name: "Technocrats Robotics" },
  { code: 'I1', name: "MIT-WPU Robocon Club" },
  { code: 'E1', name: "GTU ROBOTICS CLUB" },
  { code: 'D1', name: "Team Vulcans" },
  { code: 'G1', name: "Team Tech-Titans" },
  { code: 'K1', name: "Quazi jiyaur Rahman" },
  { code: 'E2', name: "Team Rudra" },
  { code: 'M2', name: "Team Technotix" },
  { code: 'L2', name: "Team Q-botix" },
  { code: 'B2', name: "SPCE ROBOCON" },
  { code: 'G2', name: "Team Automatons" },
  { code: 'F2', name: "Team Drishti" },
  { code: 'J2', name: "Team GCET Robocon" },
  { code: 'I2', name: "Team COEP" },
  { code: 'K2', name: "CSD Robocon NITK" },
  { code: 'H2', name: "Team (KJSSE) Robocon - KJ Somaiya School of Engineering" },
  { code: 'D2', name: "Panchjanya" },
  { code: 'C2', name: "Team Phoenix" },
  { code: 'A2', name: "Team KJSIT Robocon" },
  { code: 'H3', name: "Team RoboVyu" },
  { code: 'A3', name: "TEAM FALCON" },
  { code: 'E3', name: "Agnel Robotics Club" },
  { code: 'I3', name: "PU Robocon" },
  { code: 'M3', name: "Team RAW" },
  { code: 'D3', name: "Robotics Club IIT Delhi" },
  { code: 'L3', name: "TEAM IUST MECHBOTS" },
  { code: 'C3', name: "AMX_ROBOCON_RIT" },
  { code: 'K3', name: "Amrita Robotics" },
  { code: 'G3', name: "Team Prabal" },
  { code: 'B3', name: "Robotics IITJ" },
  { code: 'F3', name: "TeamBit" },
  { code: 'J3', name: "Team Anonymous" },
];

const matches = [
  { no: 1, red: 'A1', blue: 'A2' },
  { no: 2, red: 'B1', blue: 'B2' },
  { no: 3, red: 'C1', blue: 'C2' },
  { no: 4, red: 'D1', blue: 'D2' },
  { no: 5, red: 'E1', blue: 'E2' },
  { no: 6, red: 'F1', blue: 'F2' },
  { no: 7, red: 'G1', blue: 'G2' },
  { no: 8, red: 'H1', blue: 'H2' },
  { no: 9, red: 'I1', blue: 'I2' },
  { no: 10, red: 'J1', blue: 'J2' },
  { no: 11, red: 'K1', blue: 'K2' },
  { no: 12, red: 'L1', blue: 'L2' },
  { no: 13, red: 'M1', blue: 'M2' },
  { no: 14, red: 'A2', blue: 'A3' },
  { no: 15, red: 'B2', blue: 'B3' },
  { no: 16, red: 'C2', blue: 'C3' },
  { no: 17, red: 'D2', blue: 'D3' },
  { no: 18, red: 'E2', blue: 'E3' },
  { no: 19, red: 'F2', blue: 'F3' },
  { no: 20, red: 'G2', blue: 'G3' },
  { no: 21, red: 'H2', blue: 'H3' },
  { no: 22, red: 'I2', blue: 'I3' },
  { no: 23, red: 'J2', blue: 'J3' },
  { no: 24, red: 'K2', blue: 'K3' },
  { no: 25, red: 'L2', blue: 'L3' },
  { no: 26, red: 'M2', blue: 'M3' },
  { no: 27, red: 'A3', blue: 'A1' },
  { no: 28, red: 'B3', blue: 'B1' },
  { no: 29, red: 'C3', blue: 'C1' },
  { no: 30, red: 'D3', blue: 'D1' },
  { no: 31, red: 'E3', blue: 'E1' },
  { no: 32, red: 'F3', blue: 'F1' },
  { no: 33, red: 'G3', blue: 'G1' },
  { no: 34, red: 'H3', blue: 'H1' },
  { no: 35, red: 'I3', blue: 'I1' },
  { no: 36, red: 'J3', blue: 'J1' },
  { no: 37, red: 'K3', blue: 'K1' },
  { no: 38, red: 'L3', blue: 'L1' },
  { no: 39, red: 'M3', blue: 'M1' }
];
